
- name: Setup os
  gather_facts: true
  hosts: localhost
  vars:
    brew_packages: [ack, ant]
  roles:
  - os-base

- name: Setup shells
  gather_facts: true
  hosts: localhost
  roles:
  - shells-zsh
