---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: molecule/default/requirements.yml
  env:
    ANSIBLE_ROLES_PATH: "../.."
driver:
  name: docker
platforms:
  - name: ubuntu20
    image: ubuntu:20.04
    pre_build_image: false
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
