---
# vars file for linux_base
skip_brew: false

git_config:
  name: Zaza Saleh
  email: zaza.saleh@messagebird.com
  editor: "{{ shell_editor }}"

custom_brews:
- tap: homebrew/cask-fonts
  packages:
  - font-hack-nerd-font
- tap: gabrie30/utils
  packages:
  - ghorg
apt_sources:
- hi

apt_packages:
- ant
- build-essential
# R-lang deps
- cairo
- libxt
- pcre2
- xz

- cmake
- coreutils
- curl
- exuberant-ctags
- gcc
- git
- gnupg
- grc
- htop
- iftop
- imagemagick
- iotop
- jq
- libbz2-dev
- libncurses5-dev
- libncursesw5-dev
- libreadline-dev
- libsqlite3-dev
- libssl-dev
- libxml2
- libxml2-dev
- libxmlsec1-dev
- libxslt1-dev
- llvm
- make
- openssl
- silversearcher-ag
- software-properties-common
- tk-dev
- wget
- xz-utils
- zlib1g-dev

brew_packages:
- ack
- ant
- bash-completion
- cmake
- coreutils
- ctags-exuberant
- fasd
- fzf
- gcc
- gpg
- gping
- graphviz
- grc
- htop
- iftop
- imagemagick
- kind
- mas
- moreutils
- navi
- openssl
- reattach-to-user-namespace
- sampler
- scmpuff
- tealdeer
- the_silver_searcher
- tree
- wget
- wtfutil
- zsh-completions

cask_packages:
# - adobe-photoshop-lightroom
- alfred
# - android-studio
- appcleaner
- authy
- balsamiq-wireframes
- betterzip
- caffeine
- cheatsheet
- disk-inventory-x
- discord
# - expressvpn
- filebot
- flux
- gas-mask
# - genymotion
- google-chrome
# - google-earth-web-plugin
# - Google-photos-backup-and-sync
# - intellij-idea-ce
# - istat-menus
- Megasync
# - mongo-management-studio
- karabiner-elements
- phoenix
- product-hunt
- sequel-pro
- sketch
- sketch-toolbox
- skitch
- skyfonts
# - skype
- slack
- spectacle
- spotify
- ticktick
# - tor-browser
- Transmission
- vagrant
# - virtualbox
- vlc
- xquartz

mas_packages:
# Trello
- 1278508951

osx_defaults:
- com.apple.appstore ShowDebugMenu -bool true
- com.apple.appstore WebKitDeveloperExtras -bool true
- com.apple.dashboard mcx-disabled -bool true
- com.apple.desktopservices DSDontWriteNetworkStores -bool true
- com.apple.dock autohide -bool true
- com.apple.dock autohide-delay -float 0
- com.apple.dock autohide-time-modifier -float 0
- com.apple.dock enable-spring-load-actions-on-all-items -bool true
- com.apple.dock minimize-to-application -bool false
- com.apple.dock show-process-indicators -bool true
- com.apple.dock showhidden -bool true
- com.apple.finder FXDefaultSearchScope -string "SCcf"
- com.apple.finder QuitMenuItem -bool true
- com.apple.finder ShowPathbar -bool true
- com.apple.LaunchServices LSQuarantine -bool false
# - com.apple.universalaccess closeViewScrollWheelToggle -bool true
# - com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
- NSGlobalDomain ApplePressAndHoldEnabled -bool false
- NSGlobalDomain com.apple.springing.enabled -bool true
- NSGlobalDomain KeyRepeat -float 0
- NSGlobalDomain InitialKeyRepeat -float 0
- NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
- NSGlobalDomain NSDisableAutomaticTermination -bool true
- NSGlobalDomain com.apple.trackpad.threeFingerSwipeGesture -int 1
- com.apple.AppleMultitouchTrackpad Clicking -int 1
- com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1
- com.googlecode.iterm2 PrefsCustomFolder -string {{ iterm_config }}
- com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

