---
# defaults file for asdf
asdf_version: "v0.7.6"
asdf_user: "deploy"
asdf_legacy_version_file: "yes"

asdf_git_repo: "https://github.com/asdf-vm/asdf.git"
asdf_home: "{{ ansible_env.HOME }}"
asdf_dir: "{{ asdf_home }}/.asdf"

asdf_plugins:
  - name: golang
    brew_deps: []
    repository: "https://github.com/kennyp/asdf-golang.git"
    versions:
      - 1.15.7
    delete_versions: []
    global: 1.15.7
  - name: python
    brew_deps: []
    repository: ""
    versions:
      - 3.9.1
    delete_versions: []
    global: 3.9.1
  - name: nodejs
    brew_deps: []
    repository: "https://github.com/asdf-vm/asdf-nodejs.git"
    versions:
      - 14.15.4
    delete_versions: []
    global: 14.15.4
  - name: ruby
    brew_deps: []
    repository: "https://github.com/asdf-vm/asdf-ruby.git"
    versions:
      - 2.7.2
    delete_versions: []
    global: 2.7.2
  - name: java
    brew_deps: []
    repository: "https://github.com/halcyon/asdf-java.git"
    versions:
      - adopt-openjdk-12.0.2+10.2
    delete_versions: []
    global: adopt-openjdk-12.0.2+10.2
  - name: haskell
    brew_deps: []
    repository: "https://github.com/vic/asdf-haskell.git"
    versions:
      - 8.10.3
    delete_versions: []
    global: 8.10.3
  - name: erlang
    brew_deps: []
    repository: "https://github.com/asdf-vm/asdf-erlang.git"
    versions:
      - 23.2.3
    delete_versions: []
    global: 23.2.3
  - name: rust
    brew_deps: []
    repository: "https://github.com/code-lever/asdf-rust.git"
    versions:
      - 1.49.0
    delete_versions: []
    global: 1.49.0
  - name: helm
    brew_deps: []
    repository: "https://github.com/Antiarchitect/asdf-helm.git"
    versions:
      - 3.5.1
    delete_versions: []
    global: 3.5.1
  - name: istioctl
    brew_deps: []
    repository: "https://github.com/rafik8/asdf-istioctl.git"
    versions:
      - 1.8.2
    delete_versions: []
    global: 1.8.2
  - name: jq
    brew_deps: []
    repository: "https://github.com/ryodocx/asdf-jq.git "
    versions:
      - 1.4
    delete_versions: []
    global: 1.4
  - name: jsonnet
    brew_deps: []
    repository: "https://github.com/Banno/asdf-jsonnet.git"
    versions:
      - 0.17.0
    delete_versions: []
    global: 0.17.0
  - name: kubectl
    brew_deps: []
    repository: "https://github.com/Banno/asdf-kubectl.git"
    versions:
      - 1.20.2
    delete_versions: []
    global: 1.20.2
  - name: kubectx
    brew_deps: []
    repository: "https://github.com/trnubo/asdf-kubectx.git"
    versions:
      - 0.9.1
    delete_versions: []
    global: 0.9.1
  - name: kubefedctl
    brew_deps: []
    repository: "https://github.com/kvokka/asdf-kubefedctl.git"
    versions:
      - 0.6.1
    delete_versions: []
    global: 0.6.1
  - name: elasticsearch
    brew_deps: []
    repository: "https://github.com/asdf-community/asdf-elasticsearch.git"
    versions:
      - 7.10.2
    delete_versions: []
    global: 7.10.2
  - name: lua
    brew_deps: []
    repository: "https://github.com/Stratus3D/asdf-lua.git"
    versions:
      - 5.4.2
    delete_versions: []
    global: 5.4.2
  - name: perl
    brew_deps: []
    repository: "https://github.com/ouest/asdf-perl.git"
    versions:
      - 5.6.0
    delete_versions: []
    global: 5.6.0
  - name: R
    brew_deps: []
    repository: "https://github.com/taiar/asdf-R.git"
    versions:
      - 4.0.3
    delete_versions: []
    global: 4.0.3
  - name: skaffold
    brew_deps: []
    repository: "https://github.com/virtualstaticvoid/asdf-skaffold.git"
    versions:
      - 2.19.0
    delete_versions: []
    global: 2.19.0
  - name: terraform
    brew_deps: []
    repository: "https://github.com/Banno/asdf-hashicorp.git"
    versions:
      - 0.14.5
    delete_versions: []
    global: 0.14.5
  - name: terragrunt
    brew_deps: []
    repository: "https://github.com/lotia/asdf-terragrunt.git"
    versions:
      - 0.28.1
    delete_versions: []
    global: 0.28.1
  # - name: vagrant
  #   brew_deps: []
  #   repository: ""
  #   versions:
  #     -
  #   delete_versions: []
  #   global:
  - name: vault
    brew_deps: []
    repository: "https://github.com/Banno/asdf-hashicorp.git"
    versions:
      - 1.6.2
    delete_versions: []
    global: 1.6.2
  - name: yq
    brew_deps: []
    repository: "https://github.com/beardix/asdf-yq.git"
    versions:
      - v4.4.1
    delete_versions: []
    global: v4.4.1
  - name: consul
    brew_deps: []
    repository: "https://github.com/Banno/asdf-hashicorp.git"
    versions:
      - 1.9.3
    delete_versions: []
    global: 1.9.3
