gems:
- bundle
- chef
- compass
- tmuxinator
- zeus

npms:
- autosave
- bower
- cordova
- easymock
- forever
- generator-angular
- generator-angular-cordova
- generator-gruntfile
- generator-node
- generator-threejs
- generator-webapp
- grunt-cli
- gulp
- ionic
# - ios-deploy
# - ios-sim
- jshint
- localtunnel
# - node-inspector
- nodemon
# - phonegap
- pm2
- strider
# - webkit-devtools-agent
- yo

pips:
# - cassandra-driver
# - cql
- flake8
- neovim
- psutil
- powerline-status
- pynvim
- pyyaml
- pyinstaller
