---
- name: "ASDF Reshim"
  command: "bash -lc '{{ asdf_bin}} reshim'"

- name: Install pips
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ pips }}"

- name: Install NPMs
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npms }}"
  ignore_errors: true

- name: Install Gems
  community.general.gem:
    name: "{{ item }}"
  with_items: "{{ gems }}"
