---
- name: Install ASDF
  homebrew:
    name: asdf
    state: "{{state}}"

- name: "source asdf script"
  template:
    src: "asdf.sh.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    # group: "root"
    mode: 0755
  become: True

- include: "{{role_path}}/tasks/70-asdf/plugin.yml"
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: asdf_plugin
