---
# - name: Install ASDF
#   homebrew:
#     name: asdf
#     state: "{{state}}"

- name: Clone ASDF VM
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf_dir }}"
    version: "{{asdf_version}}"
    force: true

- name: Add ASDF to zsh
  blockinfile:
    path: "{{zsh_rc}}"
    block: |
      . $HOME/.asdf/asdf.sh

# - name: Add ASDF to Fish
#   blockinfile:
#     path: "{{fish_rc}}"
#     block: |
#       source "{{asdf_dir}}/asdf.fish"

# Configure asdf completions

- name: "source asdf script"
  template:
    src: "asdf.sh.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    # group: "root"
    mode: 0755
  become: True

- include: "{{role_path}}/tasks/70-asdf/plugin.yml"
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: asdf_plugin
