---
- name: "Install plugin {{asdf_plugin.name}}"
  command: "bash -lc 'asdf plugin-add {{ asdf_plugin.name }} {{ asdf_plugin.repository | default() }}'"
  # args:
  #   creates: "{{ asdf_dir }}/plugins/{{ asdf_plugin.name }}"
  #   # chdir: "{{ asdf_base_path }}"
  ignore_errors: true

- name: Nodejs only
  block:
    - name: Set vars
      set_fact:
        asdf_nodejs_keyring: "{{ asdf_dir }}/keyrings/nodejs"

    - name: "create keyring for Node.js keys"
      file:
        path: "{{ asdf_nodejs_keyring }}"
        state: directory
        mode: 0700

    - name: "import Node.js keys to keyring"
      command: "bash -lc '{{ asdf_dir }}/plugins/nodejs/bin/import-release-team-keyring'"
      # args:
      #   creates: "{{ asdf_nodejs_keyring }}/pubring.gpg"
      environment:
        GNUPGHOME: "{{ asdf_nodejs_keyring }}"

  when: asdf_plugin.name == "nodejs"

- name: "Install ASDF deps for {{asdf_plugin.name}}"
  homebrew:
    name: "{{asdf_plugin.brew_deps}}"
    state: "{{state}}"

- name: "Install ASDF versions for {{asdf_plugin.name}}"
  command: "bash -lc '{{asdf_bin}} install {{ asdf_plugin.name }} {{ item }}'"
  with_items: "{{ asdf_plugin.versions }}"

- name: "Remove ASDF versions for {{asdf_plugin.name}}"
  command: "bash -lc 'asdf uninstall {{ asdf_plugin.name }} {{ item }}'"
  with_items: "{{ asdf_plugin.delete_versions }}"

- name: "Set global ASDF version for {{asdf_plugin.name}}"
  command: "bash -lc 'asdf global {{ asdf_plugin.name }} {{ asdf_plugin.versions | last }}'"
