- homebrew:
    name: "{{brew_packages}}"
    state: "{{state}}"

- homebrew_cask:
    name: "{{cask_packages}}"
    state: "{{state}}"

- community.general.osx_defaults:
    domain: "{{ item.split(' ')[0] }}"
    key: "{{ item.split(' ')[1] }}"
    type: "{{ item.split(' ')[2] | regex_replace('-') }}"
    value: "{{ item.split(' ')[3] }}"
    state: "{{state}}"
  loop: "{{osx_defaults}}"

