---
- name: Install NeoVim
  homebrew:
    name: neovim
    state: "{{state}}"

- include_tasks: "config.yml"

- include_tasks: "config_Darwin.yml"
  when: ansible_os_family == 'Debian'

- name: Install Vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ vundle_path }}"
    update: no
