---
- name: Install alacritty
  when: install_alacritty
  block:
      - name: Brew install alacritty
        community.general.homebrew_cask:
          name: alacritty
          state: "{{state}}"
          install_options: force

      - name: Create a man dir for alacritty if it does not exist
        ansible.builtin.file:
          path: /usr/local/share/man/man1
          state: directory
          mode: '0755'

      - name: Create temporary directory
        tempfile:
            state: directory
        register: alacritty_dir

      - name: Clone alacritty
        git:
            force: true
            repo: '{{ alacritty_url }}'
            dest: '{{ alacritty_dir.path }}'

      - name: Build alacritty
        command: >-

        args:
            chdir: '{{ alacritty_dir.path }}'

      - name: Delete temporary directory
        file:
            state: absent
            path: '{{ alacritty_dir.path }}'

      - name: Create config directory
        become: true
        become_user: '{{ user }}'
        file:
          state: directory
          path: '{{ ansible_user_dir }}/.config/alacritty'
