- name: "{{action}} brew packages: {{brew_packages}}"
  homebrew:
    name: "{{brew_packages}}"
    state: "{{state}}"

- name: "{{action}} casks: {{cask_packages}}"
  community.general.homebrew_cask:
    name: "{{cask_packages}}"
    state: "{{state}}"
    install_options: force

- name: "{{action}} some OSX defaults"
  community.general.osx_defaults:
    domain: "{{ item.split(' ')[0] }}"
    key: "{{ item.split(' ')[1] }}"
    type: "{{ item.split(' ')[2] | regex_replace('-') }}"
    value: "{{ item.split(' ')[3] }}"
    state: "{{state}}"
  loop: "{{osx_defaults}}"

# - include: "{{role_path}}/tasks/10-os-base/install-custom-brews.yml"
#   with_items: "{{ custom_brews }}"
#   loop_control:
#     loop_var: custom_brew

# - name: Install custom brew
#   block:
#   - name: install homebrew casks
#     homebrew_tap: "name={{item.tap}}"

#   - name: "{{action}} brew packages: {{item}}"
#     homebrew:
#       name: "{{item.packages}}"
#       state: "{{state}}"
#   with_items: "{{custom_brews}}"
