galaxy_info:
  role_name: fish
  author: M Saleh
  description: Install the Friendly Interactive Shell (fish)
  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal

    - name: macOS
      versions:
        - all

  galaxy_tags:
    - system
    - shell
    - fish
