---
- name: Install Docker
  community.general.homebrew_cask:
    name: [ "docker"]
    state: "{{state}}"
    install_options: force

- name: Install Docker
  community.general.homebrew:
    name: ["docker-slim"]
    state: "{{state}}"
    install_options: force
