---
- name: Ensure that the {{ iterm2_package }} package is installed
  tags: iterm2
  homebrew_cask:
    name: "{{ iterm2_package|lower }}"
    state: present
  when: iterm2_package|length > 0

- name: Attempting to apply {{ iterm2_package }} configurations
  tags: iterm2
  osx_defaults:
    domain: "{{ iterm2_domain }}"
    key: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ iterm2_defaults }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.type is defined
    - item.value is defined
    - iterm2_defaults|length > 0
    - iterm2_domain is defined

- name: Create directory for iterm2 settings
  ansible.builtin.file:
    dest: "{{ iterm_config }}"
    src: "{{ playbook_dir }}/config/iterm2"
    state: link
    mode: '0755'

# - name: Copy iterm2 settings
#   copy:
#     src: iterm2-settings
#     dest: "{{ iterm_config }}"
