---

- include: install.yml
  tags: [ zsh, install ]

- include: configure.yml
  tags: [ zsh, configure ]

# - name: Reset antigen cache
#   command: "/bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
#   become: yes
#   changed_when: false
#   failed_when: false
#   tags: always

# # it will fail, but it install all bundles for user
# - name: Update antigen bundles
#   command: "/bin/zsh -c 'source {{ zsh_config }}; antigen update'"
#   become: yes
#   changed_when: false
#   failed_when: false
